{
 "title": "Fetch1075",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Battery Charge Percent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "battery",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_name", "operator": "=", "value": "Main Battery" }
     ]
    }
   ]
  },
  {
   "title": "Wheel Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_wheel_joint" }
     ]
    },
    {
     "alias": "r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_wheel_joint" }
     ]
    }
   ]
  },
  {
   "title": "Base Translation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "tranlation.x",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "translation.x" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "child_frame_id", "operator": "=", "value": "base_link" }
     ]
    },
    {
     "alias": "tranlation.y",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "translation.y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "child_frame_id", "operator": "=", "value": "base_link" }
     ]
    }
   ]
  },
  {
   "title": "Head Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "head_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "head_pan_joint" }
     ]
    },
    {
     "alias": "head_tilt_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "head_tilt_joint" }
     ]
    }
   ]
  },
  {
   "title": "Arm Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "shoulder_pan_joint" }
     ]
    },
    {
     "alias": "shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "shoulder_lift_joint" }
     ]
    },
    {
     "alias": "upperarm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "upperarm_roll_joint" }
     ]
    },
    {
     "alias": "elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "elbow_flex_joint" }
     ]
    },
    {
     "alias": "forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "forearm_roll_joint" }
     ]
    },
    {
     "alias": "wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "wrist_flex_joint" }
     ]
    },
    {
     "alias": "wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "wrist_roll_joint" }
     ]
    }
   ]
  },
  {
   "title": "Torso Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "torso_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "torso_lift_joint" }
     ]
    }
   ]
  },
  {
   "title": "Wheel Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_wheel_joint" }
     ]
    },
    {
     "alias": "r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_wheel_joint" }
     ]
    }
   ]
  },
  {
   "title": "Base Rotation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "rotation.z",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "rotation.z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "child_frame_id", "operator": "=", "value": "base_link" }
     ]
    }
   ]
  },
  {
   "title": "Head Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "head_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "head_pan_joint" }
     ]
    },
    {
     "alias": "head_tilt_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "head_tilt_joint" }
     ]
    }
   ]
  },
  {
   "title": "Arm Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "shoulder_pan_joint" }
     ]
    },
    {
     "alias": "shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "shoulder_lift_joint" }
     ]
    },
    {
     "alias": "upperarm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "upperarm_roll_joint" }
     ]
    },
    {
     "alias": "elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "elbow_flex_joint" }
     ]
    },
    {
     "alias": "forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "forearm_roll_joint" }
     ]
    },
    {
     "alias": "wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "wrist_flex_joint" }
     ]
    },
    {
     "alias": "wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "wrist_roll_joint" }
     ]
    }
   ]
  },
  {
   "title": "Torso Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "torso_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "torso_lift_joint" }
     ]
    }
   ]
  }
 ]
}