{
 "title": "PR1012",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Battery charge percent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "battery 0",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "query": "SELECT mean(\"charge_percent\") FROM \"battery_states\" WHERE (\"battery_id\" = '0') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "battery 1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "battery 2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "battery 3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "battery_states",
     "select": [
      [
       { "params": [ "charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "battery_id", "operator": "=", "value": "3" }
     ]
    }
   ]
  },
  {
   "title": "Base Translation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "translation.x",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "translation.x" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "child_frame_id", "operator": "=", "value": "base_footprint" }
     ]
    },
    {
     "alias": "translation.y",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "translation.y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "child_frame_id", "operator": "=", "value": "base_footprint" }
     ]
    }
   ]
  },
  {
   "title": "Base rotation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "rotation.z",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "map_transform",
     "select": [
      [
       { "params": [ "rotation.z" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "child_frame_id", "operator": "=", "value": "base_footprint" }
     ]
    }
   ]
  },
  {
   "title": "Head Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "head_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "head_pan_joint" }
     ]
    },
    {
     "alias": "head_tilt_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "head_tilt_joint" }
     ]
    }
   ]
  },
  {
   "title": "Left Arm Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "l_elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_elbow_flex_joint" }
     ]
    },
    {
     "alias": "l_forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_forearm_roll_joint" }
     ]
    },
    {
     "alias": "l_shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_shoulder_lift_joint" }
     ]
    },
    {
     "alias": "l_shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_shoulder_pan_joint" }
     ]
    },
    {
     "alias": "l_upper_arm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_upper_arm_roll_joint" }
     ]
    },
    {
     "alias": "l_wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_wrist_flex_joint" }
     ]
    },
    {
     "alias": "l_wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_wrist_roll_joint" }
     ]
    }
   ]
  },
  {
   "title": "Right Arm Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "r_elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_elbow_flex_joint" }
     ]
    },
    {
     "alias": "r_forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_forearm_roll_joint" }
     ]
    },
    {
     "alias": "r_shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_shoulder_lift_joint" }
     ]
    },
    {
     "alias": "r_shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_shoulder_pan_joint" }
     ]
    },
    {
     "alias": "r_upper_arm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_upper_arm_roll_joint" }
     ]
    },
    {
     "alias": "r_wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_wrist_flex_joint" }
     ]
    },
    {
     "alias": "r_wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_wrist_roll_joint" }
     ]
    }
   ]
  },
  {
   "title": "Torso Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "torso_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "torso_lift_joint" }
     ]
    }
   ]
  },
  {
   "title": "Wheel Joint Position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "radian" }
   ],
   "targets": [
    {
     "alias": "bl_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "bl_caster_l_wheel_joint" }
     ]
    },
    {
     "alias": "bl_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "bl_caster_r_wheel_joint" }
     ]
    },
    {
     "alias": "bl_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "bl_caster_rotation_joint" }
     ]
    },
    {
     "alias": "br_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "br_caster_l_wheel_joint" }
     ]
    },
    {
     "alias": "br_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "br_caster_r_wheel_joint" }
     ]
    },
    {
     "alias": "br_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "br_caster_rotation_joint" }
     ]
    },
    {
     "alias": "fl_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fl_caster_l_wheel_joint" }
     ]
    },
    {
     "alias": "fl_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fl_caster_r_wheel_joint" }
     ]
    },
    {
     "alias": "fl_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fl_caster_rotation_joint" }
     ]
    },
    {
     "alias": "fr_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fr_caster_l_wheel_joint" }
     ]
    },
    {
     "alias": "fr_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fr_caster_r_wheel_joint" }
     ]
    },
    {
     "alias": "fr_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "position" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fr_caster_rotation_joint" }
     ]
    }
   ]
  },
  {
   "title": "Head Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "head_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "head_pan_joint" }
     ]
    },
    {
     "alias": "head_tilt_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "head_tilt_joint" }
     ]
    }
   ]
  },
  {
   "title": "Left Arm Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "l_elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_elbow_flex_joint" }
     ]
    },
    {
     "alias": "l_forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_forearm_roll_joint" }
     ]
    },
    {
     "alias": "l_shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_shoulder_lift_joint" }
     ]
    },
    {
     "alias": "l_shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_shoulder_pan_joint" }
     ]
    },
    {
     "alias": "l_upper_arm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_upper_arm_roll_joint" }
     ]
    },
    {
     "alias": "l_wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_wrist_flex_joint" }
     ]
    },
    {
     "alias": "l_wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "l_wrist_roll_joint" }
     ]
    }
   ]
  },
  {
   "title": "Right Arm Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "r_elbow_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_elbow_flex_joint" }
     ]
    },
    {
     "alias": "r_forearm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_forearm_roll_joint" }
     ]
    },
    {
     "alias": "r_shoulder_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_shoulder_lift_joint" }
     ]
    },
    {
     "alias": "r_shoulder_pan_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_shoulder_pan_joint" }
     ]
    },
    {
     "alias": "r_upper_arm_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_upper_arm_roll_joint" }
     ]
    },
    {
     "alias": "r_wrist_flex_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_wrist_flex_joint" }
     ]
    },
    {
     "alias": "r_wrist_roll_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "r_wrist_roll_joint" }
     ]
    }
   ]
  },
  {
   "title": "Torso Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "torso_lift_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "torso_lift_joint" }
     ]
    }
   ]
  },
  {
   "title": "Wheel Joint Effort",
   "type": "graph",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "bl_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "bl_caster_l_wheel_joint" }
     ]
    },
    {
     "alias": "bl_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "bl_caster_r_wheel_joint" }
     ]
    },
    {
     "alias": "bl_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "bl_caster_rotation_joint" }
     ]
    },
    {
     "alias": "br_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "br_caster_l_wheel_joint" }
     ]
    },
    {
     "alias": "br_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "br_caster_r_wheel_joint" }
     ]
    },
    {
     "alias": "br_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "br_caster_rotation_joint" }
     ]
    },
    {
     "alias": "fl_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fl_caster_l_wheel_joint" }
     ]
    },
    {
     "alias": "fl_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fl_caster_r_wheel_joint" }
     ]
    },
    {
     "alias": "fl_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fl_caster_rotation_joint" }
     ]
    },
    {
     "alias": "fr_caster_l_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fr_caster_l_wheel_joint" }
     ]
    },
    {
     "alias": "fr_caster_r_wheel_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fr_caster_r_wheel_joint" }
     ]
    },
    {
     "alias": "fr_caster_rotation_joint",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "joint_states",
     "select": [
      [
       { "params": [ "effort" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "joint_name", "operator": "=", "value": "fr_caster_rotation_joint" }
     ]
    }
   ]
  }
 ]
}