name: CI

on:
  push:
  pull_request:

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic, ROS_REPO: testing, UPSTREAM_WORKSPACE: '.ci.rosinstall'}
          - {ROS_DISTRO: kinetic, ROS_REPO: main, UPSTREAM_WORKSPACE: '.ci.rosinstall'}
          - {ROS_DISTRO: melodic, ROS_REPO: testing, UPSTREAM_WORKSPACE: '.ci.rosinstall'}
          - {ROS_DISTRO: melodic, ROS_REPO: main, UPSTREAM_WORKSPACE: '.ci.rosinstall'}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
